server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
      generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: 1133
    driver-class-name: 'org.postgresql.Driver'
  mail:
    host: smtp.gmail.com
    port: 587
    username: MY
    password: MY
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB